// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/access" | "/admin" | "/admin/audit" | "/admin/cases" | "/admin/cases/[id]" | "/admin/directory" | "/admin/finance" | "/admin/login" | "/admin/payouts" | "/admin/reports" | "/admin/staff" | "/admin/users" | "/app" | "/austin" | "/austin/unlock" | "/dallas" | "/dallas/unlock" | "/denver" | "/denver/unlock" | "/houston" | "/houston/unlock" | "/lesson/[lessonId]" | "/lifeline" | "/login" | "/los-angeles" | "/los-angeles/unlock" | "/paths/[pathSlug]" | "/profile" | "/signup"
type AppRouteHandlerRoutes = "/api/access" | "/api/admin/audit" | "/api/admin/cases" | "/api/admin/cases/[id]" | "/api/admin/cases/[id]/allocate" | "/api/admin/cases/[id]/dispatch" | "/api/admin/cases/[id]/notes" | "/api/admin/cases/staff" | "/api/admin/directory" | "/api/admin/directory/[id]" | "/api/admin/finance" | "/api/admin/finance/payout-config" | "/api/admin/finance/pool" | "/api/admin/login" | "/api/admin/payouts" | "/api/admin/session" | "/api/admin/staff" | "/api/admin/staff/[staffId]" | "/api/admin/stats" | "/api/admin/stats/activity" | "/api/admin/stats/reports" | "/api/admin/stats/trends" | "/api/admin/users" | "/api/admin/users/[userId]" | "/api/auth/login" | "/api/auth/register" | "/api/auth/session" | "/api/chat" | "/api/city-access/[slug]" | "/api/payout/request" | "/api/progress/complete" | "/api/progress/list" | "/api/stress-signal" | "/api/user/ensure" | "/api/user/profile"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/access": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/cases": {}
  "/admin/cases/[id]": { "id": string; }
  "/admin/directory": {}
  "/admin/finance": {}
  "/admin/login": {}
  "/admin/payouts": {}
  "/admin/reports": {}
  "/admin/staff": {}
  "/admin/users": {}
  "/api/access": {}
  "/api/admin/audit": {}
  "/api/admin/cases": {}
  "/api/admin/cases/[id]": { "id": string; }
  "/api/admin/cases/[id]/allocate": { "id": string; }
  "/api/admin/cases/[id]/dispatch": { "id": string; }
  "/api/admin/cases/[id]/notes": { "id": string; }
  "/api/admin/cases/staff": {}
  "/api/admin/directory": {}
  "/api/admin/directory/[id]": { "id": string; }
  "/api/admin/finance": {}
  "/api/admin/finance/payout-config": {}
  "/api/admin/finance/pool": {}
  "/api/admin/login": {}
  "/api/admin/payouts": {}
  "/api/admin/session": {}
  "/api/admin/staff": {}
  "/api/admin/staff/[staffId]": { "staffId": string; }
  "/api/admin/stats": {}
  "/api/admin/stats/activity": {}
  "/api/admin/stats/reports": {}
  "/api/admin/stats/trends": {}
  "/api/admin/users": {}
  "/api/admin/users/[userId]": { "userId": string; }
  "/api/auth/login": {}
  "/api/auth/register": {}
  "/api/auth/session": {}
  "/api/chat": {}
  "/api/city-access/[slug]": { "slug": string; }
  "/api/payout/request": {}
  "/api/progress/complete": {}
  "/api/progress/list": {}
  "/api/stress-signal": {}
  "/api/user/ensure": {}
  "/api/user/profile": {}
  "/app": {}
  "/austin": {}
  "/austin/unlock": {}
  "/dallas": {}
  "/dallas/unlock": {}
  "/denver": {}
  "/denver/unlock": {}
  "/houston": {}
  "/houston/unlock": {}
  "/lesson/[lessonId]": { "lessonId": string; }
  "/lifeline": {}
  "/login": {}
  "/los-angeles": {}
  "/los-angeles/unlock": {}
  "/paths/[pathSlug]": { "pathSlug": string; }
  "/profile": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
