// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access">> = Specific
  const handler = {} as typeof import("../../app/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cases/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cases/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/cases/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cases">> = Specific
  const handler = {} as typeof import("../../app/admin/cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/directory">> = Specific
  const handler = {} as typeof import("../../app/admin/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payouts">> = Specific
  const handler = {} as typeof import("../../app/admin/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff">> = Specific
  const handler = {} as typeof import("../../app/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/austin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/austin">> = Specific
  const handler = {} as typeof import("../../app/austin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/austin/unlock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/austin/unlock">> = Specific
  const handler = {} as typeof import("../../app/austin/unlock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dallas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dallas">> = Specific
  const handler = {} as typeof import("../../app/dallas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dallas/unlock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dallas/unlock">> = Specific
  const handler = {} as typeof import("../../app/dallas/unlock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/denver/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/denver">> = Specific
  const handler = {} as typeof import("../../app/denver/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/denver/unlock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/denver/unlock">> = Specific
  const handler = {} as typeof import("../../app/denver/unlock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/houston/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/houston">> = Specific
  const handler = {} as typeof import("../../app/houston/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/houston/unlock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/houston/unlock">> = Specific
  const handler = {} as typeof import("../../app/houston/unlock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lesson/[lessonId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lesson/[lessonId]">> = Specific
  const handler = {} as typeof import("../../app/lesson/[lessonId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lifeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lifeline">> = Specific
  const handler = {} as typeof import("../../app/lifeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/los-angeles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/los-angeles">> = Specific
  const handler = {} as typeof import("../../app/los-angeles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/los-angeles/unlock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/los-angeles/unlock">> = Specific
  const handler = {} as typeof import("../../app/los-angeles/unlock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/paths/[pathSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/paths/[pathSlug]">> = Specific
  const handler = {} as typeof import("../../app/paths/[pathSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/access">> = Specific
  const handler = {} as typeof import("../../app/api/access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/api/admin/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cases/[id]/allocate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cases/[id]/allocate">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cases/[id]/allocate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cases/[id]/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cases/[id]/dispatch">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cases/[id]/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cases/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cases/[id]/notes">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cases/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cases/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cases/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cases/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cases">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cases/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cases/staff">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cases/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/directory/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/directory/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/directory/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/directory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/directory">> = Specific
  const handler = {} as typeof import("../../app/api/admin/directory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance/payout-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/payout-config">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance/payout-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance/pool/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/pool">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance/pool/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payouts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session">> = Specific
  const handler = {} as typeof import("../../app/api/admin/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/staff/[staffId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/staff/[staffId]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/staff/[staffId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/staff">> = Specific
  const handler = {} as typeof import("../../app/api/admin/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/stats/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats/activity">> = Specific
  const handler = {} as typeof import("../../app/api/admin/stats/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/stats/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats/reports">> = Specific
  const handler = {} as typeof import("../../app/api/admin/stats/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/stats/trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats/trends">> = Specific
  const handler = {} as typeof import("../../app/api/admin/stats/trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/city-access/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/city-access/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/city-access/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payout/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payout/request">> = Specific
  const handler = {} as typeof import("../../app/api/payout/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/progress/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/progress/complete">> = Specific
  const handler = {} as typeof import("../../app/api/progress/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/progress/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/progress/list">> = Specific
  const handler = {} as typeof import("../../app/api/progress/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stress-signal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stress-signal">> = Specific
  const handler = {} as typeof import("../../app/api/stress-signal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/ensure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/ensure">> = Specific
  const handler = {} as typeof import("../../app/api/user/ensure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
